name: Dev

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
  publish:
   needs: build
   runs-on: self-hosted
   permissions:
      packages: write 
   steps:
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Remove github source
      run: dotnet nuget remove source github
      continue-on-error: true
    - name: Add github source
      run:  dotnet nuget add source --username NickPolyder --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/NickPolyder/index.json"
    - name: Publish Nuget
      run: dotnet nuget push "nuget-packages/*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
