name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:   
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Remove github source
      run: dotnet nuget remove source github
      continue-on-error: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
   
  tests:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Get Current version
      id: get-app-version
      run: |
        version=$(~/powershell/pwsh ./tools/Get-Version.ps1)
        echo '::set-output name=AppVersion::'$version
    - name: Coverage
      run: ~/powershell/pwsh -File ./tools/Execute-Coverage-pipeline.ps1 -HistoryPath /home/pi/Projects/NP-ObjectComparison/History -Tag '${{ github.run_number }}_${{ github.run_id }},${{steps.get-app-version.outputs.AppVersion}}'
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: CoverageReport # Artifact name        
        path: ./tools/coverageReport # Directory containing files to upload
      
