name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  publish:
   needs: build
   runs-on: self-hosted
   permissions:
      packages: write 
   steps:
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish Nuget
      run: dotnet nuget push "nuget-packages/*.nupkg"  --api-key ${{ secrets.NUGET_API_TOKEN }} --source "nuget" --skip-duplicate
    - name: Publish Symbols
      run: dotnet nuget push "nuget-packages/*.snupkg"  --api-key ${{ secrets.NUGET_API_TOKEN }} --source "nuget" --skip-duplicate